/**
* Valve Mod Gearbox Weapon Constants
* Gearbox.inc Mod Weapon Constants
* Credits:amxmodx.org/api/hlsdk_const/__raw,
* SPiNX 12-29-2019.
#define HLI_HEALTHKIT       1
#define HLI_ANTIDOTE        2
#define HLI_SECURITY        3
#define HLI_BATTERY         4

#define HLW_NONE            0
#define HLW_CROWBAR         1
#define HLW_GLOCK           2
#define HLW_PYTHON          3
#define HLW_MP5             4
#define HLW_CHAINGUN        5
#define HLW_CROSSBOW        6
#define HLW_SHOTGUN         7
#define HLW_RPG             8
#define HLW_GAUSS           9
#define HLW_EGON            10
#define HLW_HORNETGUN       11
#define HLW_HANDGRENADE     12
#define HLW_TRIPMINE        13
#define HLW_SATCHEL         14
#define HLW_SNARK           15
*/
#define HLW_GRAPPLE         16
#define HLW_357             17
#define HLW_PIPEWRENCH      18
#define HLW_KNIFE           0x0019
#define HLW_DISPLACER       20
#define HLW_SHOCKROACH      22
#define HLW_SPORE           23
#define HLW_SNIPER          25
#define HLW_PENGUIN         26
/*
#define HLW_SUIT            31 //Unproven
#define HLW_ALLWEAPONS      (~(1<<HLW_SUIT))
*/
#define HLW_ALLOP4WEAPONS   (~(1>>HLW_SNARK)) 
